package onl.tesseract.srp.domain.job;

import java.util.*;

/**
 * Represents a player's job progression including level, XP, skills, and reputation.
 */
public class PlayerJobProgression {
    private final UUID playerID;
    private int level;
    private int xp;
    private int skillPoints;
    private final List<JobSkill> skills;
    private final Map<EnumJob, Double> reputationByJob;

    public PlayerJobProgression(UUID playerID) {
        this(playerID, 1, 0, 0, new ArrayList<>(), new HashMap<>());
    }

    public PlayerJobProgression(UUID playerID, int level, int xp, int skillPoints,
                                 List<JobSkill> skills, Map<EnumJob, Double> reputationByJob) {
        this.playerID = playerID;
        this.level = level;
        this.xp = xp;
        this.skillPoints = skillPoints;
        this.skills = new ArrayList<>(skills);
        this.reputationByJob = new HashMap<>();
        for (EnumJob job : EnumJob.values()) {
            this.reputationByJob.put(job, reputationByJob.getOrDefault(job, 1.0));
        }
    }

    public UUID getPlayerID() {
        return playerID;
    }

    public int getLevel() {
        return level;
    }

    public int getXp() {
        return xp;
    }

    public int getSkillPoints() {
        return skillPoints;
    }

    public List<JobSkill> getSkills() {
        return Collections.unmodifiableList(skills);
    }

    public Map<EnumJob, Double> getReputationByJob() {
        return reputationByJob;
    }

    /**
     * Give (or delete) XP to the player. If amount is positive and enough to increase the level, the level is updated,
     * and the xp decreased. Removing more than the current XP amount will set XP to 0 without decreasing the level.
     * @return Amount of passed levels
     */
    public int addXp(int amount) {
        this.xp += amount;
        int passedLevel = 0;
        while (this.xp >= getXpForLevel(this.level + 1)) {
            this.xp -= getXpForLevel(this.level + 1);
            this.level++;
            passedLevel++;
        }
        this.xp = Math.max(0, this.xp);
        this.skillPoints += passedLevel;
        return passedLevel;
    }

    public void addLevel(int amount) {
        this.level += amount;
        this.level = Math.max(1, this.level);
    }

    public void addSkillPoints(int points) {
        this.skillPoints += points;
        this.skillPoints = Math.max(0, this.skillPoints);
    }

    public boolean addSkill(JobSkill skill) {
        if (skill.getCost() > skillPoints || !isSkillAvailable(skill)) {
            return false;
        }
        if (hasSkill(skill)) {
            return false;
        }
        skills.add(skill);
        skillPoints -= skill.getCost();
        return true;
    }

    public boolean hasSkill(JobSkill skill) {
        return skills.contains(skill);
    }

    public boolean isSkillAvailable(JobSkill skill) {
        JobSkill parent = skill.getParent();
        if (parent == null) {
            return true;
        }
        return isSkillAvailable(parent);
    }

    /**
     * Get the added loot chance bonus coefficient generated by the player's skills
     * @return Bonus coefficient, starting at 0 for no bonus.
     */
    public float getLootChanceBonus(JobHarvestEvent event) {
        return (float) skills.stream()
                .mapToDouble(skill -> skill.getBonus().getLootChanceBonus(event))
                .sum();
    }

    /**
     * Get the added money bonus coefficient generated by the player's skills
     * @return Bonus coefficient, starting at 0 for no bonus.
     */
    public float getMoneyBonus(JobHarvestEvent event) {
        return (float) skills.stream()
                .mapToDouble(skill -> skill.getBonus().getMoneyBonus(event))
                .sum();
    }

    /**
     * Get the added quality bonus coefficient generated by the player's skills
     * @return Bonus coefficient, starting at 0 for no bonus.
     */
    public int getQualityBonus(JobHarvestEvent event) {
        return (int) skills.stream()
                .mapToInt(skill -> skill.getBonus().getQualityBonus(event))
                .sum();
    }

    private int getXpForLevel(int level) {
        return 100 * (level - 1);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PlayerJobProgression that = (PlayerJobProgression) o;
        return xp == that.xp && level == that.level;
    }

    @Override
    public int hashCode() {
        return Objects.hash(xp, level);
    }

    @Override
    public String toString() {
        return "PlayerJobProgression(xp=" + xp + ", level=" + level + ")";
    }
}

