<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>onl.tesseract.srp</groupId>
        <artifactId>srp-parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>customItem-adapter</artifactId>
    <packaging>jar</packaging>

    <name>SRP CustomItem Adapter</name>

    <build>
        <sourceDirectory>${project.basedir}/src/main/java</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>onl.tesseract.srp</groupId>
            <artifactId>customItem-domain</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>onl.tesseract</groupId>
            <artifactId>tesseract-core</artifactId>
            <version>5.0.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${springboot-context.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- ItemsAdder -->
        <dependency>
            <groupId>dev.lone</groupId>
            <artifactId>api-itemsadder</artifactId>
            <scope>provided</scope>
            <version>4.0.10</version>
        </dependency>
    </dependencies>
</project>

