name: TesseractSRP2
version: '0.1-SNAPSHOT'
main: onl.tesseract.srp.TesseractSRP
api-version: '1.21'
commands:
  staffSrp:
    permission: staff
    description: Commandes staff du SRP
    aliases:
      - staffs