name: TesseractSRP2
version: '0.1-SNAPSHOT'
main: onl.tesseract.srp.TesseractSRP
api-version: '1.21'
depend: [TesseractCore, MCKotlin-Paper, Citizens]
commands:
  staffSrp:
    permission: staff
    description: Commandes staff du SRP
    aliases:
      - staffs
  jobskill:
    description: Ouvrir le menu des compétences de métier
  campement:
    permission: campement
    description: Gère les campements
    aliases:
      - c
      - camp
  rank:
    permission: rank
    description: Ouvre le menu des grades