package onl.tesseract.srp.domain.commun.enum

enum class CreationResult {
    ALREADY_HAS_TERRITORY, INVALID_WORLD, NEAR_SPAWN, NAME_TAKEN,
    NOT_ENOUGH_MONEY, RANK_TOO_LOW, TOO_CLOSE_TO_OTHER_TERRITORY, ON_OTHER_TERRITORY,
    SUCCESS
}
