<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>onl.tesseract.srp</groupId>
        <artifactId>srp-parent</artifactId>
        <version>0.1-SNAPSHOT</version>
    </parent>

    <artifactId>skill-adapter</artifactId>
    <packaging>jar</packaging>

    <name>SRP Skill Adapter</name>

    <build>
        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>onl.tesseract.srp</groupId>
            <artifactId>skill-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>onl.tesseract.srp</groupId>
            <artifactId>customItem-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${springboot-context.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>onl.tesseract.srp</groupId>
            <artifactId>common-adapter</artifactId>
            <version>0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>onl.tesseract.srp</groupId>
            <artifactId>territory-domain</artifactId>
            <version>0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>onl.tesseract</groupId>
            <artifactId>core</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>

