name: Build project with Maven

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  deteck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Detekt
        run: curl -sSLO https://github.com/detekt/detekt/releases/download/v1.23.8/detekt-cli-1.23.8.zip && unzip detekt-cli-1.23.8.zip
      - name: Analyze
        run: ./detekt-cli-1.23.8/bin/detekt-cli -r xml:reports/detekt.xml
      - name: Upload report
        uses: actions/upload-artifact@v4.6.2
        with:
          path: reports/detekt.xml
          name: detekt.xml
          retention-days: 2

  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Restore detekt report
        uses: actions/download-artifact@v4
        with:
          name: detekt.xml
      - name: Build project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=TesseractFR_TesseractSRP2
